// Web Container App — public ingress, mounts /data/uploads from the
// shared Azure Files share, reads master key + DATABASE_URL from Key Vault
// via its user-assigned managed identity.
//
// Resources / replicas are conservative defaults — bump in main.bicep if
// your tenant is large.

@description('Resource name prefix')
param namePrefix string

@description('Azure region')
param location string

@description('Container Apps Environment ID')
param caeId string

@description('Storage name registered on the Container Apps Environment (the uploads share)')
param uploadsStorageName string

@description('Managed identity resource ID for this app')
param identityId string

@description('Managed identity client ID (for KV references)')
param identityClientId string

@description('Container image full reference, e.g. <acr>.azurecr.io/identityatlas:latest')
param image string

@description('ACR login server (used for the registry credential entry)')
param acrLoginServer string

@description('Key Vault URI (https://<name>.vault.azure.net/)')
param keyVaultUri string

@description('Postgres FQDN')
param pgFqdn string

@description('Postgres admin username')
param pgUsername string

@description('Postgres database name')
param pgDatabaseName string

@description('Postgres admin password (from Key Vault via getSecret).')
@secure()
param pgPassword string

@description('Master key (32-byte base64). Pulled in from KV by main.bicep.')
@secure()
param masterKey string

@description('CPU cores per replica')
param cpu string = '1'

@description('Memory per replica')
param memory string = '2Gi'

@description('Minimum number of replicas')
@minValue(1)
param minReplicas int = 1

@description('Maximum number of replicas')
@minValue(1)
param maxReplicas int = 3

@description('Optional ingress IP whitelist (CIDR list). Empty = allow all.')
param allowedIpCidrs array = []

resource app 'Microsoft.App/containerApps@2024-10-02-preview' = {
  name: '${namePrefix}-web'
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${identityId}': {}
    }
  }
  properties: {
    managedEnvironmentId: caeId
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 3001
        transport: 'auto'
        traffic: [
          { latestRevision: true, weight: 100 }
        ]
        ipSecurityRestrictions: [for (cidr, i) in allowedIpCidrs: {
          name: 'allow-${i}'
          action: 'Allow'
          ipAddressRange: cidr
        }]
      }
      registries: [
        {
          server: acrLoginServer
          identity: identityId
        }
      ]
      secrets: [
        {
          // Composed here so the password lives only inside the Container
          // App's secret store, never in a module output. The linter can't
          // track @secure-ness through string interpolation, but the only
          // secret part (pgPassword) IS marked @secure() above.
          name: 'database-url'
          #disable-next-line use-secure-value-for-secure-inputs
          value: 'postgres://${pgUsername}:${pgPassword}@${pgFqdn}:5432/${pgDatabaseName}?sslmode=require'
        }
        {
          name: 'master-key'
          value: masterKey
        }
      ]
    }
    template: {
      containers: [
        {
          name: 'web'
          image: image
          resources: {
            cpu: json(cpu)
            memory: memory
          }
          env: [
            { name: 'NODE_ENV',                 value: 'production' }
            { name: 'USE_SQL',                  value: 'true' }
            { name: 'PORT',                     value: '3001' }
            { name: 'BEHIND_TLS',               value: 'true' }
            { name: 'DATABASE_URL',             secretRef: 'database-url' }
            { name: 'IDENTITY_ATLAS_MASTER_KEY', secretRef: 'master-key' }
            // Built-in worker API key is generated by bootstrap.js on first
            // boot and persisted to /data/uploads/.builtin-worker-key on
            // the shared Azure Files share. The worker container reads the
            // same file — no env var needed.
            { name: 'AUTH_ENABLED',             value: 'false' }
            { name: 'AZURE_KEY_VAULT_URI',      value: keyVaultUri }
            { name: 'AZURE_CLIENT_ID',          value: identityClientId }
          ]
          volumeMounts: [
            { volumeName: 'uploads', mountPath: '/data/uploads' }
          ]
          probes: [
            {
              type: 'Liveness'
              httpGet: { path: '/api/health', port: 3001 }
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 5
            }
            {
              type: 'Readiness'
              httpGet: { path: '/api/health', port: 3001 }
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
            }
          ]
        }
      ]
      volumes: [
        {
          name: 'uploads'
          storageType: 'AzureFile'
          storageName: uploadsStorageName
        }
      ]
      scale: {
        minReplicas: minReplicas
        maxReplicas: maxReplicas
        rules: [
          {
            name: 'http-scale'
            http: {
              metadata: {
                concurrentRequests: '50'
              }
            }
          }
        ]
      }
    }
  }
}

output appId string = app.id
output appName string = app.name
output appFqdn string = app.properties.configuration.ingress.fqdn
output appUrl string = 'https://${app.properties.configuration.ingress.fqdn}'
