// @vitest-environment jsdom
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { createElement as h } from 'react';
import ContextDetailPage from './ContextDetailPage';
import {
  renderWithProviders,
  makeAuthFetch,
  jsonResponse,
  screen,
  fireEvent,
  waitFor,
  userEvent,
} from '@ui/test-utils/renderWithProviders';

// useFeatures uses the global `fetch` (not authFetch) to hit /api/features.
// Stub it so the riskScoring flag is available and predictable.
beforeEach(() => {
  global.fetch = vi.fn(async () =>
    jsonResponse({ riskScoring: true, accountLinking: true }),
  );
});
afterEach(() => {
  vi.restoreAllMocks();
});

// A loaded "generated" context with a couple of members + a sub-context.
const generatedDetail = {
  attributes: {
    id: 'ctx-1',
    variant: 'generated',
    targetType: 'Identity',
    contextType: 'Cluster',
    displayName: 'Engineering Cluster',
    description: 'A generated cluster of engineers.',
    scopeSystemName: 'EntraID',
    sourceAlgorithmName: 'kmeans',
    sourceAlgorithmDisplayName: 'K-Means Clustering',
    directMemberCount: 2,
    totalMemberCount: 5,
    department: 'Engineering',          // surfaces in the attributes grid
    confidence: 0.92,                    // surfaces in the attributes grid
  },
  subContexts: [
    { id: 'ctx-child', displayName: 'Backend Squad', memberCount: 3 },
  ],
};

const members = {
  total: 2,
  data: [
    {
      id: 'm-1',
      displayName: 'Alice Engineer',
      email: 'alice@example.com',
      jobTitle: 'Staff Engineer',
      principalType: 'User',
      accountEnabled: true,
      addedBy: 'algorithm',
    },
    {
      id: 'm-2',
      displayName: 'Bob Builder',
      email: 'bob@example.com',
      jobTitle: 'Engineer',
      principalType: 'User',
      accountEnabled: false,
      addedBy: 'analyst',
    },
  ],
};

const timeline = {
  events: [],
  addedCount: 0,
  removedCount: 0,
  changedCount: 0,
  sinceDays: 90,
};

const riskData = {
  riskScore: 70,
  riskTier: 'High',
  riskScoredAt: '2026-06-01T10:00:00Z',
  riskDirectScore: 30,
  riskMembershipScore: 20,
  riskStructuralScore: 10,
  riskPropagatedScore: 10,
};

// Order matters: more-specific substrings (/members, /timeline) before the
// bare /api/contexts/ctx-1 detail key.
function routes(overrides = {}) {
  return makeAuthFetch({
    '/api/risk-scores/contexts/ctx-1': riskData,
    '/api/contexts/ctx-1/members': members,
    '/api/contexts/ctx-1/timeline': timeline,
    '/api/contexts/ctx-1': generatedDetail,
    ...overrides,
  });
}

const baseProps = {
  contextId: 'ctx-1',
  cachedData: null,
  onCacheData: () => {},
  onClose: () => {},
  onOpenDetail: () => {},
};

describe('ContextDetailPage (mounted)', () => {
  it('shows the loading state before the detail fetch resolves', () => {
    // authFetch that never resolves keeps it in the loading branch.
    const authFetch = vi.fn(() => new Promise(() => {}));
    renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch } });
    expect(screen.getByText(/Loading context details/i)).toBeInTheDocument();
  });

  it('renders the header, provenance and members after load', async () => {
    renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch: routes() } });

    // Header
    expect(await screen.findByText('Engineering Cluster')).toBeInTheDocument();
    expect(screen.getByText('Cluster')).toBeInTheDocument();
    expect(screen.getByText('EntraID')).toBeInTheDocument();
    // Provenance line for a generated context
    expect(screen.getByText(/Generated by the "K-Means Clustering" plugin/i)).toBeInTheDocument();
    // Description card
    expect(screen.getByText('A generated cluster of engineers.')).toBeInTheDocument();

    // Default tab is "relationships" — sub-contexts + members render.
    expect(await screen.findByText(/Sub-contexts \(1\)/i)).toBeInTheDocument();
    expect(screen.getByText('Backend Squad')).toBeInTheDocument();
    expect(await screen.findByText('Alice Engineer')).toBeInTheDocument();
    expect(screen.getByText('Bob Builder')).toBeInTheDocument();
    expect(screen.getByText('Active')).toBeInTheDocument();
    expect(screen.getByText('Disabled')).toBeInTheDocument();
  });

  it('switches to the Attributes tab and shows cleaned attributes + generated actions', async () => {
    renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch: routes() } });
    const user = userEvent.setup();

    await screen.findByText('Engineering Cluster');
    await user.click(screen.getByRole('tab', { name: /Attributes/i }));

    // Attributes grid shows non-system attrs only.
    expect(await screen.findByText('department')).toBeInTheDocument();
    expect(screen.getByText('Engineering')).toBeInTheDocument();
    expect(screen.getByText('confidence')).toBeInTheDocument();
    // Generated-context actions block.
    expect(screen.getByText('Generated context — actions')).toBeInTheDocument();
  });

  it('switches to the Timeline tab and triggers the timeline fetch', async () => {
    const authFetch = routes();
    renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch } });
    const user = userEvent.setup();

    await screen.findByText('Engineering Cluster');
    await user.click(screen.getByRole('tab', { name: /Timeline/i }));

    await waitFor(() =>
      expect(authFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/contexts/ctx-1/timeline'),
      ),
    );
  });

  it('shows the Risk tab when risk data + feature flag are present', async () => {
    renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch: routes() } });
    const user = userEvent.setup();

    await screen.findByText('Engineering Cluster');
    const riskTab = await screen.findByRole('tab', { name: /^Risk$/i });
    await user.click(riskTab);

    expect(await screen.findByText('Risk Assessment')).toBeInTheDocument();
  });

  it('filters members via the search box', async () => {
    const authFetch = routes();
    renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch } });

    await screen.findByText('Alice Engineer');
    fireEvent.change(screen.getByLabelText('Search members'), {
      target: { value: 'alice' },
    });

    await waitFor(() =>
      expect(authFetch).toHaveBeenCalledWith(
        expect.stringContaining('search=alice'),
      ),
    );
  });

  it('toggles include-sub-contexts which re-queries with the descendants param', async () => {
    const authFetch = routes();
    renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch } });

    await screen.findByText('Alice Engineer');
    fireEvent.click(screen.getByLabelText(/Include sub-contexts/i));

    await waitFor(() =>
      expect(authFetch).toHaveBeenCalledWith(
        expect.stringContaining('include=descendants'),
      ),
    );
  });

  it('opens a sub-context via onOpenDetail when clicked', async () => {
    const onOpenDetail = vi.fn();
    renderWithProviders(
      h(ContextDetailPage, { ...baseProps, onOpenDetail }),
      { auth: { authFetch: routes() } },
    );
    const user = userEvent.setup();

    await user.click(await screen.findByText('Backend Squad'));
    expect(onOpenDetail).toHaveBeenCalledWith('context', 'ctx-child', 'Backend Squad');
  });

  it('wraps the members table in a horizontally-scrolling container', async () => {
    const { container } = renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch: routes() } });

    await screen.findByText('Alice Engineer');
    const wrapper = container.querySelector('table').closest('.overflow-x-auto');
    expect(wrapper).toBeTruthy();
  });

  it('renders the empty members state', async () => {
    const authFetch = routes({
      '/api/contexts/ctx-1/members': { total: 0, data: [] },
    });
    renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch } });

    expect(await screen.findByText('No members found.')).toBeInTheDocument();
  });

  it('renders the error state and retries on click', async () => {
    let calls = 0;
    const authFetch = vi.fn(async (url, opts = {}) => {
      if (String(url).includes('/api/contexts/ctx-1') &&
          !url.includes('/members') && !url.includes('/timeline')) {
        calls += 1;
        if (calls === 1) return jsonResponse({ error: 'boom' }, { ok: false, status: 500 });
        return jsonResponse(generatedDetail);
      }
      if (url.includes('/members')) return jsonResponse(members);
      if (url.includes('/timeline')) return jsonResponse(timeline);
      if (url.includes('/risk-scores')) return jsonResponse(riskData);
      return jsonResponse({}, { ok: false, status: 404 });
    });

    renderWithProviders(h(ContextDetailPage, baseProps), { auth: { authFetch } });
    const user = userEvent.setup();

    expect(await screen.findByText('Failed to load context')).toBeInTheDocument();
    expect(screen.getByText('HTTP 500')).toBeInTheDocument();

    await user.click(screen.getByText('Retry'));
    // Second fetch succeeds → header renders.
    expect(await screen.findByText('Engineering Cluster')).toBeInTheDocument();
  });

  it('caches the loaded detail via onCacheData', async () => {
    const onCacheData = vi.fn();
    renderWithProviders(
      h(ContextDetailPage, { ...baseProps, onCacheData }),
      { auth: { authFetch: routes() } },
    );

    await screen.findByText('Engineering Cluster');
    expect(onCacheData).toHaveBeenCalledWith('ctx-1', 'context', generatedDetail);
  });
});
