import { useState } from 'react';
import ManualContextEditor from './contexts/ManualContextEditor';

// ─── Attributes tab ───────────────────────────────────────────────────────────
// Inline editor (manual + generated contexts), generated-context delete actions,
// and the cleaned attribute grid.

const SYSTEM_COLS = new Set([
  'SysStartTime', 'SysEndTime', 'ValidFrom', 'ValidTo',
  // New-shape fields already surfaced in the header — don't repeat in the
  // attributes grid.
  'id', 'variant', 'targetType', 'contextType', 'displayName', 'description',
  'parentContextId', 'scopeSystemId', 'scopeSystemName', 'sourceAlgorithmId',
  'sourceAlgorithmName', 'sourceAlgorithmDisplayName', 'sourceRunId',
  'createdByUser', 'ownerUserId', 'externalId', 'parentDisplayName',
]);

export function cleanAttributes(attrs) {
  if (!attrs) return {};
  const clean = {};
  for (const [key, value] of Object.entries(attrs)) {
    if (!SYSTEM_COLS.has(key) && value != null && value !== '') {
      clean[key] = value;
    }
  }
  return clean;
}

export default function ContextAttributesTab({ contextId, attrs, isManual, isGenerated, authFetch, onUpdated, onDeleted }) {
  const cleaned = cleanAttributes(attrs);
  const hasAttrs = Object.keys(cleaned).length > 0;

  return (
    <>
      {/* Inline editor — manual and generated (plugin) contexts are editable;
          synced contexts are read-only. */}
      {(isManual || isGenerated) && (
        <ManualContextEditor
          contextId={contextId}
          attrs={attrs}
          onUpdated={onUpdated}
          onDeleted={onDeleted}
        />
      )}

      {/* Generated-context actions — delete only; everything else is owned
          by the plugin that produced this row. */}
      {isGenerated && (
        <GeneratedContextActions
          contextId={contextId}
          attrs={attrs}
          authFetch={authFetch}
          onDeleted={onDeleted}
        />
      )}

      {hasAttrs && (
        <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-6">
          <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">Attributes</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-2">
            {Object.entries(cleaned).map(([key, value]) => (
              <div key={key} className="flex items-baseline gap-2 py-1">
                <span className="text-xs text-gray-500 dark:text-gray-400 font-medium min-w-[140px]">{key}</span>
                <span className="text-sm text-gray-900 dark:text-white break-all">{typeof value === 'object' ? JSON.stringify(value) : String(value)}</span>
              </div>
            ))}
          </div>
        </div>
      )}
      {!hasAttrs && !isManual && !isGenerated && (
        <div className="bg-white dark:bg-gray-800 border border-dashed border-gray-200 dark:border-gray-700 rounded-lg p-6 text-center text-sm text-gray-600 dark:text-gray-500">No additional attributes.</div>
      )}
    </>
  );
}

// ─── Generated-context actions (delete) ───────────────────────────────────
// Analysts sometimes want to prune low-signal generated trees (a cluster of
// junk, an OU that doesn't model anything useful). Deleting is permitted
// but we call out the caveat: re-running the same plugin will re-create
// the row. For persistent removal, the user should tune plugin parameters
// (e.g., add a noise token to additionalStopwords).
function GeneratedContextActions({ contextId, attrs, authFetch, onDeleted }) {
  const [confirming, setConfirming] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [error, setError] = useState(null);

  async function doDelete() {
    setDeleting(true); setError(null);
    try {
      const r = await authFetch(`/api/contexts/${contextId}`, { method: 'DELETE' });
      if (!r.ok && r.status !== 204) {
        const body = await r.json().catch(() => ({}));
        throw new Error(body.error || `HTTP ${r.status}`);
      }
      onDeleted?.();
    } catch (err) {
      setError(err.message || 'Delete failed');
      setDeleting(false);
    }
  }

  const algo = attrs.sourceAlgorithmDisplayName || attrs.sourceAlgorithmName || 'its plugin';

  return (
    <div className="bg-white dark:bg-gray-800 border border-sky-200 dark:border-sky-700 rounded-lg p-6">
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300">Generated context — actions</h3>
        <span className="text-[10px] text-sky-700 dark:text-sky-300 bg-sky-50 dark:bg-sky-900/30 border border-sky-200 dark:border-sky-700 rounded px-1.5 py-0.5">
          Generated by {algo}
        </span>
      </div>
      <p className="text-[11px] text-gray-600 dark:text-gray-400 mb-3">
        Delete this context if it's noise. Re-running <code className="px-1 bg-gray-100 dark:bg-gray-700 rounded">{attrs.sourceAlgorithmName || 'the plugin'}</code>{' '}
        with the same parameters will recreate it — to keep it gone, also tune the plugin
        parameters (e.g., add noise tokens to <code className="px-1 bg-gray-100 dark:bg-gray-700 rounded">additionalStopwords</code>)
        before re-running.
      </p>

      {error && <div className="mb-3 text-xs text-red-700 dark:text-red-400 bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-700 rounded px-2 py-1">{error}</div>}

      {confirming ? (
        <div className="flex items-center gap-2">
          <span className="text-[11px] text-red-700 dark:text-red-400">Delete this context and all its descendants + members?</span>
          <button
            onClick={doDelete}
            disabled={deleting}
            className="px-3 py-1 text-xs rounded bg-red-600 dark:bg-red-700 text-white disabled:opacity-50 hover:bg-red-700 dark:hover:bg-red-600"
          >
            {deleting ? 'Deleting…' : 'Yes, delete'}
          </button>
          <button
            onClick={() => setConfirming(false)}
            className="px-3 py-1 text-xs rounded border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700/50 text-gray-700 dark:text-gray-300"
          >Cancel</button>
        </div>
      ) : (
        <button
          onClick={() => setConfirming(true)}
          className="text-[11px] text-red-600 dark:text-red-400 hover:text-red-700 dark:hover:text-red-400"
        >Delete context…</button>
      )}
    </div>
  );
}
