<#
.SYNOPSIS
    Sync Azure Resource Manager RBAC into Identity Atlas via the Ingest API.

.DESCRIPTION
    Emits the Azure scope hierarchy (management groups → subscriptions → resource groups →
    optionally resources) as Resources linked by `Contains` relationships, plus one synthetic
    "<role> @ <scope>" capability-resource per declared role assignment, with the assignment
    itself. Inheritance (a role at a parent scope applying to descendants) is NOT materialised —
    the effective-access engine computes it on demand from the Contains hierarchy.

    Auth: service-principal client-credentials against management.azure.com (reuses
    Get-FGAccessToken). Reader at the crawled scope is sufficient.

    This entry point is thin orchestration: config → connect → register → run each phase →
    finalize. All phase logic lives in dot-sourced siblings so it is unit-testable:
      AzureRMCrawler.Functions.ps1  – pure helpers (scope-node id, resource-type parsing, …)
      AzureRMCrawler.Transform.ps1  – pure record-shapers (New-Azure*Record, Get-AzureRolePlane)
      AzureRMCrawler.Phases.ps1     – the $Ctx state object + Sync-AzureRM* phase functions

    See docs/sync/building-a-crawler.md → "Feeding the Effective-Access Engine".
#>

[CmdletBinding()]
Param(
    [Parameter(Mandatory)] [string]$ApiBaseUrl,
    [Parameter(Mandatory)] [string]$ApiKey,
    [Parameter(Mandatory)] [int]$JobId,
    [Parameter(Mandatory)] [string]$ConfigPath
)

$ErrorActionPreference = 'Stop'
$ApiBaseUrl = $ApiBaseUrl.TrimEnd('/')

# Round-trip counter (bumped by the request helpers) for the per-phase timing report.
$Global:AzCallCount = 0

# ─── Shared helpers ──────────────────────────────────────────────
. (Join-Path $PSScriptRoot '..' 'shared' 'Invoke-CrawlerIngest.ps1')
. (Join-Path $PSScriptRoot '..' 'shared' 'Get-CapabilityId.ps1')
. (Join-Path $PSScriptRoot 'AzureRMCrawler.Functions.ps1')
. (Join-Path $PSScriptRoot 'AzureRMCrawler.Transform.ps1')
. (Join-Path $PSScriptRoot 'AzureRMCrawler.Phases.ps1')
# Get-AzureRMHelpers.ps1 (ARM auth + enumeration) and Get-AzureRGHelpers.ps1 (Resource Graph reads)
# are dot-sourced automatically by the dispatcher (same-folder libraries).

$Config = Resolve-AzureRMConfig -ConfigPath $ConfigPath

Write-Host "`n=== Azure RM Crawler (Resource Graph) ===" -ForegroundColor Cyan

# ─── Connectivity + auth ─────────────────────────────────────────
Update-CrawlerProgress -Step 'Authenticating to Azure RM' -Pct 2
Connect-AzureRMSession -Config $Config

# ─── Register system + build the cross-phase state ───────────────
$SystemId = Register-AzureRMSystem -Config $Config
$Ctx = New-AzureRMState -Config $Config -SystemId $SystemId

# ─── Phases ──────────────────────────────────────────────────────
# Scope nodes + Contains edges are deduped and ingested AFTER the assignment phase: that
# phase adds management-group / resource scope nodes on demand, because an assignment's
# declared scope can sit above (an MG / tenant root) or below (a single resource) what
# scope discovery enumerated.
Sync-AzureRMScopes          -Ctx $Ctx
Sync-AzureRMRoleDefinitions -Ctx $Ctx
Sync-AzureRMAssignments     -Ctx $Ctx

Optimize-AzureRecords       -Ctx $Ctx
Send-AzureScopeRecords      -Ctx $Ctx

# Orphan handling: principals the Entra ID crawler hasn't loaded (deleted SPs with dangling
# assignments, or principals intentionally out of scope). Runs between the scope send and
# the grant send so pruned grants/resources are never emitted.
Resolve-AzureRMOrphans        -Ctx $Ctx
Send-AzurePrincipalsAndGrants -Ctx $Ctx

# Contexts are NOT emitted here — they are derived data. Context trees (scope hierarchy,
# resource type) are generated by context-algorithm plugins from the scope Resources +
# Contains edges this crawler emits, keeping the crawler to source data only.

# ─── Refresh views (also bumps the effective-access cache version) + complete ──
Complete-AzureRMRun -ApiBaseUrl $ApiBaseUrl -ApiKey $ApiKey
